# Site settings
baseurl = "https://www.curso-r.com/"
languageCode = "en-us"
title = "Curso-R"
disqusShortname = "curso-r-com"
googleAnalytics = "UA-87272102-2"
contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    # Meta
    title = "Curso-R"
    subtitle = "Neste portal disponibilizamos todo o nosso conteúdo e material de aula. Fique a vontade para sugerir edições e contribuir com novos tópicos!"
    github = "https://github.com/curso-r"
    facebook = "https://www.facebook.com/cursodeR/"
    twitter = "https://twitter.com/curso_r"
    logo = "assets/logocursor.png"
    disable_codefolding = false
    codefolding_nobutton = true
    codefolding_show = "Codigo"
    custom_css = ["codefolding.css"]

    
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "author"
